version: '3.5'

services:

    nginx:
      image: ${COMPOSE_PROJECT_NAME}-nginx:latest
      build:
        context: ./docker/
        args:
          BUILD_ARGUMENT_ENV: staging
        dockerfile: ./nginx/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}-nginx
      restart: always
      ports:
        - "${WEB_PORT_HTTP}:80"
        - "${WEB_PORT_SSL}:443"
      volumes:
        - ./:/var/www/html:ro,cached
      depends_on:
        - laravel
      networks:
        - laravel

    laravel: &laravel-template
      image: ${COMPOSE_PROJECT_NAME}-laravel:latest
      build:
        context: .
        args:
          BUILD_ARGUMENT_ENV: staging
          HOST_UID: ${HOST_UID}
          HOST_GID: ${HOST_GID}
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}-laravel
      restart: always
      depends_on:
        - mysql
      networks:
        - laravel

    ### Cron tasks
    supervisord:
      <<: *laravel-template
      container_name: ${COMPOSE_PROJECT_NAME}-supervisord
      expose: []
      command: ["/usr/bin/supervisord"]

    mysql:
      image: mysql:${MYSQL_VERSION}
      platform: linux/x86_64
      container_name: ${COMPOSE_PROJECT_NAME}-mysql
      restart: always
      command: --innodb-use-native-aio=${INNODB_USE_NATIVE_AIO:-1} --sql_mode=${SQL_MODE:-"ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"}
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: laravel
      volumes:
        - ./storage/mysql-data:/var/lib/mysql:delegated
      networks:
        - laravel

networks:
  laravel:
    name: laravel
